name: Spring Boot CI/CD Pipeline with Zero Downtime

on:
  push:
    branches: [ "master", "steve" ]

jobs:
  build:
    name: Build, Push, and Deploy Spring Boot App
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      # 3. Gradle Build
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # 4. Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

      # 6. Deploy Spring Boot App on Port 8080
      - name: Deploy Spring Boot App on Port 8080
        run: |
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d --name springboot-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
